Repository KVeitch/palette-picker-back-end, pull requests merged in 2019-12, with the labels that each got.

#13 Create initial migtation
  db/migrations/20191202153352_initial.js
Labels: MVP

#17 Seeding
  db/migrations/20191202153352_initial.js
  db/seeds/dev/data/palettes.csv
  db/seeds/dev/data/paletts.js
  db/seeds/dev/data/projects.js
  db/seeds/dev/data/users.js
  db/seeds/dev/projects_palettes.js
  docs/Schema-with-users.jpeg
Labels: MVP

#21 Testing kav
  app.js
  app.test.js
  db/migrations/20191202153352_initial.js
Labels: MVP, Testing

#23 Testing kav
  app.js
  app.test.js
Labels: Endpoints, MVP

#24 Corrects Test for endpoints
  app.js
  app.test.js
Labels: MVP, bug

#31 Endpoints2
  app.js
Labels: Endpoints, MVP

#32 Endpoints
  app.js
  app.test.js
Labels: bug

#34 Readme
  README.md
Labels: documentation

#35 Endpoints3
  app.js
Labels: Endpoints
